package com.iptvapp.sync

import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * Sender half of the cast sealed box. The receiver half is MKCrypto in the MKTV TV app
 * (Tizen/webOS `js/crypto.js`) — the two must stay byte-for-byte compatible, and
 * CastBoxTest pins the shared construction with vectors generated from that file.
 *
 * Why not AES-GCM: the receiving TV is a 2015 Samsung running Tizen 2.3, whose WebKit has no
 * WebCrypto at all (measured — `crypto.subtle` and `crypto.webkitSubtle` are both absent, and
 * there is no Promise to drive them with). It does have a real `crypto.getRandomValues`. So the
 * scheme is built on SHA-256 alone, which that engine can implement in plain ES5 in a form
 * checkable against published test vectors, and which maps onto MessageDigest/Mac here without
 * adding a dependency to either project.
 *
 *   K   shared 256-bit secret, generated by the RECEIVER and carried here in the QR code —
 *       it crosses the air gap between that screen and this camera, never the network
 *   Ke  = HMAC(K, "mktv-cast-enc-v1")     encryption subkey
 *   Km  = HMAC(K, "mktv-cast-mac-v1")     MAC subkey, independent of Ke
 *   N   16 random bytes chosen here, fresh for every seal
 *   S_i = HMAC(Ke, N || be32(i))          keystream blocks
 *   C   = P XOR (S_0 || S_1 || …)         counter mode over a PRF
 *   T   = HMAC(Km, N || C)                encrypt-then-MAC, covers nonce and ciphertext
 *
 * Each key seals exactly one short payload for one session, so the keystream reuse that would
 * otherwise make counter mode dangerous cannot arise.
 */
object CastBox {

    private const val ENC_LABEL = "mktv-cast-enc-v1"
    private const val MAC_LABEL = "mktv-cast-mac-v1"
    private const val NONCE_LEN = 16
    private const val KEY_LEN = 32

    private val rng = SecureRandom()

    private fun hmac(key: ByteArray, msg: ByteArray): ByteArray {
        val mac = Mac.getInstance("HmacSHA256")
        // An all-zero key is a legal HMAC key but SecretKeySpec rejects an EMPTY one; callers
        // never pass empty here, and letting it throw beats silently keying with something else.
        mac.init(SecretKeySpec(key, "HmacSHA256"))
        return mac.doFinal(msg)
    }

    private fun be32(i: Int) = byteArrayOf(
        (i ushr 24).toByte(), (i ushr 16).toByte(), (i ushr 8).toByte(), i.toByte()
    )

    private fun keystream(ke: ByteArray, nonce: ByteArray, len: Int): ByteArray {
        val out = ByteArray(len)
        var filled = 0
        var counter = 0
        while (filled < len) {
            val block = hmac(ke, nonce + be32(counter))
            val take = minOf(block.size, len - filled)
            System.arraycopy(block, 0, out, filled, take)
            filled += take
            counter++
        }
        return out
    }

    /** base64url without padding — matches MKCrypto.b64uEncode on the receiver. */
    private val B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"

    fun b64uEncode(bytes: ByteArray): String {
        val sb = StringBuilder()
        var i = 0
        while (i < bytes.size) {
            val b0 = bytes[i].toInt() and 0xff
            val b1 = if (i + 1 < bytes.size) bytes[i + 1].toInt() and 0xff else -1
            val b2 = if (i + 2 < bytes.size) bytes[i + 2].toInt() and 0xff else -1
            sb.append(B64[b0 shr 2])
            if (b1 < 0) { sb.append(B64[(b0 and 3) shl 4]); break }
            sb.append(B64[((b0 and 3) shl 4) or (b1 shr 4)])
            if (b2 < 0) { sb.append(B64[(b1 and 15) shl 2]); break }
            sb.append(B64[((b1 and 15) shl 2) or (b2 shr 6)])
            sb.append(B64[b2 and 63])
            i += 3
        }
        return sb.toString()
    }

    fun b64uDecode(s: String): ByteArray {
        val out = java.io.ByteArrayOutputStream()
        var acc = 0
        var bits = 0
        for (ch in s) {
            val v = B64.indexOf(ch)
            if (v < 0) continue          // tolerate stray padding/whitespace
            acc = (acc shl 6) or v
            bits += 6
            if (bits >= 8) {
                bits -= 8
                out.write((acc shr bits) and 0xff)
            }
        }
        return out.toByteArray()
    }

    /** Seals [plaintext] under [key], producing "nonce.ciphertext.tag" in base64url. */
    fun seal(key: ByteArray, plaintext: String): String {
        val ke = hmac(key, ENC_LABEL.toByteArray(Charsets.UTF_8))
        val km = hmac(key, MAC_LABEL.toByteArray(Charsets.UTF_8))
        val nonce = ByteArray(NONCE_LEN).also { rng.nextBytes(it) }
        val pt = plaintext.toByteArray(Charsets.UTF_8)
        val ks = keystream(ke, nonce, pt.size)
        val ct = ByteArray(pt.size) { (pt[it].toInt() xor ks[it].toInt()).toByte() }
        val tag = hmac(km, nonce + ct)
        return "${b64uEncode(nonce)}.${b64uEncode(ct)}.${b64uEncode(tag)}"
    }

    /** Inverse of [seal]; returns null if malformed or if the MAC doesn't verify. Only used by
     * tests on this side — the TV is the real opener — but kept here so both directions of the
     * construction are pinned by CastBoxTest rather than only the one this app exercises. */
    fun open(key: ByteArray, sealed: String): String? {
        val parts = sealed.split(".")
        if (parts.size != 3) return null
        val nonce = b64uDecode(parts[0])
        val ct = b64uDecode(parts[1])
        val tag = b64uDecode(parts[2])
        if (nonce.size != NONCE_LEN || tag.size != 32) return null

        val ke = hmac(key, ENC_LABEL.toByteArray(Charsets.UTF_8))
        val km = hmac(key, MAC_LABEL.toByteArray(Charsets.UTF_8))
        if (!MessageDigest.isEqual(hmac(km, nonce + ct), tag)) return null   // constant time

        val ks = keystream(ke, nonce, ct.size)
        return String(ByteArray(ct.size) { (ct[it].toInt() xor ks[it].toInt()).toByte() }, Charsets.UTF_8)
    }

    /**
     * Splits a scanned QR payload into its session code and session key.
     *
     * New receivers encode "<code>.<base64url key>". A bare code comes from a receiver old
     * enough to predate the sealed box; [key] is null there so the caller can refuse rather
     * than quietly fall back to putting a credential-bearing URL in Firestore.
     */
    data class ScannedTarget(val code: String, val key: ByteArray?) {
        // data class with a ByteArray — override so equality is by content, not reference
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is ScannedTarget) return false
            return code == other.code && (key?.contentEquals(other.key ?: ByteArray(0)) ?: (other.key == null))
        }
        override fun hashCode(): Int = 31 * code.hashCode() + (key?.contentHashCode() ?: 0)
    }

    fun parseScanned(scanned: String): ScannedTarget {
        val trimmed = scanned.trim()
        val dot = trimmed.indexOf('.')
        if (dot <= 0) return ScannedTarget(trimmed.lowercase(), null)
        val code = trimmed.substring(0, dot).lowercase()
        val key = b64uDecode(trimmed.substring(dot + 1))
        return if (key.size == KEY_LEN) ScannedTarget(code, key) else ScannedTarget(code, null)
    }
}
